graph TD
  WidgetsService-->WidgetsComponent

  WidgetsComponent-->|"[widgets] is a Widgets[]"|WidgetsList
  WidgetsComponent-->|"set [widget] <br>is a function"|WidgetDetail

  WidgetsList-->|"(selected)"|WidgetsComponent
  WidgetsList-->|"(deleted)"|WidgetsComponent
  WidgetsList-->|"(performAction)?"|WidgetsDetail

  WidgetDetail-->|"(saved)"|WidgetsComponent
  WidgetDetail-->|"(cancelled)"|WidgetsComponent
  WidgetDetail-->|"(goForIt)?"|WidgetsComponent
